name: Cross-only compilation environment

on:
  push:
    branches:
      - master
      # Stable branches such as 0.56 or the eventual 1.0
      - '[0-9]+.[0-9]+'
  pull_request:

jobs:
  cross-only-armhf:
    runs-on: ubuntu-latest
    container: mesonbuild/eoan:latest
    steps:
    - run: |
        apt-get -y purge clang gcc gdc
        apt-get -y autoremove
    - uses: actions/checkout@v2
    - name: Run tests
      run: bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./run_tests.py $CI_ARGS --cross ubuntu-armhf.json --cross-only'
