name: OS Comp Tests

on: [push, pull_request]

jobs:
  xenial:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends python3-setuptools python3-pip g++ gfortran gobjc gobjc++ zlib1g-dev python-dev python3-dev libboost-all-dev
    - name: Remove GitHub boost version
      run: sudo rm -rf /usr/local/share/boost
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v1
    - name: Python version
      run: python3 --version
    - name: Ninja version
      run: ninja --version
    - name: Run tests
      run: python3 run_tests.py
      env:
        CI: '1'
        OLD_OS_CI: '1'

  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container: mensinda/arch:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: ./run_tests.py
      env:
        CI: '1'
